# Generated by Django 5.0.2 on 2024-02-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
